### ISSUE TITLE
post.delete() method can only trigger if both id and bulk are present

### ISSUE THREAD

**Issue by Ochmar** [ayrshare/social-post-api-python#1]
From docs:

> deleteResponse = social.delete({
>     # Required
>     'id': "POST ID",                          **# optional, but required if "bulk" not present**
>     'bulk': ["Post ID 1", "Post ID 2", ...]   **# optional, but required if "id" not present**
>   })

But from code:
https://github.com/ayrshare/social-post-api-python/blob/9a91d781b8128043c1360f4920321d322a74b9ab/ayrshare/ayrshare.py#L41&#L45
   ```
 def delete(self, data):
        if "id" not in data or "bulk" not in data:
            return ERROR_MSG

        return doDelete("delete", data, self.headers)
```
The 'or' makes it that both id and bulk have to be passed in data, which is wrong.
That should be **and** instead of **or**.
Please correct me if i'm wrong

**Comment by shyam-ayrshare** [comment]
We have removed this check. Thanks.
