### ISSUE TITLE
Method signatures in the python bindings has a dangerous flaw.

### ISSUE THREAD

**Issue by dchaplinsky** [ayrshare/social-post-api-python#9]
Basically all your methods look like this:
```python
    def user(self, params={}):
        return doGet("user", params, self.headers)
```

passing and empty dict is a dangerous thing see for example https://stackoverflow.com/questions/1132941/the-mutable-default-argument-in-python

**Comment by shyam-ayrshare** [comment]
This has been fixed now. Thanks for bringing this up.
